export { HomePage } from './HomePage'
export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
export { PropertyPage } from './PropertyPage'
export { DashboardPage } from './DashboardPage'
export { ResetPasswordPage } from './ResetPasswordPage'
export { VerifyEmailPage } from './VerifyEmailPage'
